### ISSUE TITLE
Anchor behavior change breaks RDoc

### ISSUE THREAD

**Issue by kou** [ruby/strscan#10]
#6 breaks RDoc. It uses `\A`. So we should keep the previous behavior by default.

**Comment by kou** [comment]
1.0.1 with #6 is yanked for now.

**Comment by jneen** [comment]
Hi @kou! Could you provide a link to the parser that this breaks? Perhaps an option like `relative_anchors: true` to the constructor (or a method like `use_relative_anchors!`) could resolve the issue?

**Comment by kou** [comment]
I misunderstood.
It's not general Racc breakage. It just breaks RDoc.
https://github.com/ruby/rdoc/blob/master/lib/rdoc/rd/inline_parser.ry#L362

I'll add `fixed_anchor` option to the constructor.

**Comment by jneen** [comment]
Okay! With that change, it would also be nice to add some way to feature-detect this, maybe by adding a `#fixed_anchor?` message to the scanner object, such that we could test `#respond_to?`?

**Comment by kou** [comment]
You can use `StringScanner.method_defined?(:fixed_anchor?)`.
