### ISSUE TITLE
warning: already initialized constant StringScanner::Version

### ISSUE THREAD

**Issue by dabroz** [ruby/strscan#102]
When using this gem with ruby 3.3.1 I'm getting

```
.../.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/strscan-3.1.0/lib/strscan.bundle: warning: already initialized constant StringScanner::Version
```

**Comment by kou** [comment]
Could you provide a way to reproduce this?

**Comment by kinsomicrote** [comment]
I am also seeing the same thing on my Rails project:
```
.../.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/strscan-3.1.0/lib/strscan.bundle: warning: already initialized constant StringScanner::Version
.../.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/strscan-3.1.0/lib/strscan.bundle: warning: already initialized constant StringScanner::Id
```
I get this when I run my test suite - rspec.
In my Rails project, `strscan` is used by `rexml` which is used by `rubocop`.

**Comment by dabroz** [comment]
I've created a minified version of the project here: https://github.com/dabroz/strscantest
To see this behaviour, clone the repo, then run `bundle; rspec test.rb`
There is also a Dockerfile you can test wit h`./dockme` 

But the strangest thing is that there have to be very specific circumstances to observe this problem:
- only with Ruby 3.3
- only directly on Mac, not on Linux via Docker
- only when using bootsnap
- only when using rbenv
- only when running `rspec` via shim (when running `bundle exec rspec` it works fine)

**Comment by kou** [comment]
Why do you want to use `rspec` not `bundle exec rspec`?
In general, you should use `bundle exec ...` when you use `Gemfile` to manage your dependency.

**Comment by dabroz** [comment]
Overall sure, but this happens even on a clean rbenv install, where only gems are the ones installed from the Gemfile.

**Comment by kou** [comment]
Could you show `gem list` output on the reproduced environment?

**Comment by dabroz** [comment]
Bingo!

```
strscan (3.1.0, default: 3.0.7)
```

After pinning it:
```
gem 'strscan', '3.0.7'
```
it doesn't show the warning anymore. I had to pin rubocop to an earlier version (`1.63.0`) as the latest requires the latest strscan:
```
    rubocop was resolved to 1.64.0, which depends on
      rexml (>= 3.2.5, < 4.0) was resolved to 3.2.8, which depends on
        strscan (>= 3.0.9)
```

So can we do anything if a newer version of a default gem is needed?

**Comment by kou** [comment]
The next REXML version that includes https://github.com/ruby/rexml/issues/132 will change the situation. It relaxes required strscan version.
(But `bundle exec rspec` is preferred.)

**Comment by Soeren-Klatt** [comment]
Got the same message when running only rspec without bundle exec. The message appeared after going from ruby 3.1.6 to ruby 3.2.0.
Im using strscan (3.1.0)

**Comment by kou** [comment]
If `gem list | grep strscan` has multiple versions, you must use `bundle exec` to choose only one strscan.

**Comment by kou** [comment]
This is not a strscan problem.
