### ISSUE TITLE
strscan.c not under 2-clause BSD license

### ISSUE THREAD

**Issue by shyouhei** [ruby/strscan#12]
> You can distribute/modify this program under the terms of
> the Ruby License. For details, see the file COPYING.

https://github.com/ruby/strscan/blob/master/ext/strscan/strscan.c#L7-L8

I am not sure whether the copyright holder (@aamine) thinks this library is under Ruby's or BSD license.  The current situation shall be wrong either ways.  Must be fixed accordingly.

**Comment by aamine** [comment]
Both licenses are acceptable for me anyway.

**Comment by mrkn** [comment]
I'll rewrite the comment in strscan.c to fix this issue?

**Comment by mrkn** [comment]
Fixed in a999f2c.

**Comment by kou** [comment]
We need to update the following line in `COYPING`:

```diff
-Ruby is copyrighted free software by Yukihiro Matsumoto <matz@netlab.jp>.
+StringScanner is copyrighted free software by Minero Aoki.
```

**Comment by mrkn** [comment]
@kou Good catch! Thanks!
