### ISSUE TITLE
Break it out of ruby or do not, there is no try

### ISSUE THREAD

**Issue by jasonperrone** [ruby/strscan#42]
Not sure if this belongs here or in ruby bugs, but strscan is broken out as its own gem in ruby gems and is now at 3.0.3. Meanwhile, it's still in the Ruby stdlib at 3.0.1. Does anybody else see the conflict here? Sure did at one of my clients, where a Rails app failed to start because net-imap brought in 3.0.3 of strscan through bundler, but 3.0.1 was still there as a default gem from Ruby 3.1.2.  These folks too: https://openbuildservice.org/2022/05/11/post-mortem/

**Comment by nevans** [comment]
Your situation might be different, but it looks like there was an issue with psych (which rubygems uses) loading strscan too soon (before rubygems had the chance to pick the locked version).  (You might be able to confirm psych is what's loading it first, using the debugger or monkey patching `require`.)

You might try: 1) upgrade to psych 4.0.4, which doesn't load strscan so early, that's assuming psych is what's required the conflicting version.  You might also want to try upgrading to the latest versions of rubygems and bundler.  Or 2) downgrade to strscan 3.0.1... you might need to update the Gemfile.lock manually, depending on how badly rubygems and bundler are affected. or 3) as a temporary workaround, it might work to forcibly load the version you want before anything else can change it, e.g. by using the `RUBYLIB` and `RUBYOPT` env vars.

**Comment by jasonperrone** [comment]
In our case, it's net-imap bringing in strscan as a bundled gem. I had to lock to 3.0.1 in Gemfile in order to force the bundled version of strscan to match the version of the default gem. My understanding is that bundler itself uses strscan and so it activates the stdlib version before it loads the gem.

**Comment by eregon** [comment]
I think newer Bundler shouldn't load psych or strscan, and so using a more recent bundler should avoid this issue.
I found https://github.com/rubygems/rubygems/pull/3638 regarding Bundler loading psych.
This should be best filed as a Bundler issue at https://github.com/rubygems/rubygems/issues, there is nothing strscan can do here, so I close this one.
